version: '3.9'

services:
  phpmyadmin:
    container_name: phpmyadmin
    hostname: phpmyadmin
    image: phpmyadmin:latest
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
    network_mode: bridge
    expose:
      - 80
    volumes:
      - /run/mysqld/mysqld.sock:/tmp/mysql.sock:ro
    environment:
      PMA_HOST: localhost
      PMA_USER: $MYSQL_USERNAME
      PMA_PASSWORD: $MYSQL_PASSWORD
    labels:
      traefik.enable: true
      traefik.http.routers.pma.rule: Host(`pma.$DOMAIN`)
      traefik.http.routers.pma.entrypoints: https
      traefik.http.routers.pma.tls: true
      traefik.http.routers.pma.middlewares: authelia@docker
