# /etc/dnsmasq.d/02-hostname.conf
# # https://qiita.com/bmj0114/items/9c24d863bcab1a634503#4-add-wildcard-dns-recode-properly
# address=/$DOMAIN/$DOMAIN_LODAL_IP

version: '3.9'

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
    network_mode: bridge
    ports:
      - 53:53/tcp
      - 53:53/udp
    expose:
      - 80
    volumes:
      - /etc/pihole:/etc/pihole:rw
      - /etc/dnsmasq.d:/etc/dnsmasq.d:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /run/mysqld/mysqld.sock:/tmp/mysql.sock:ro
    environment:
      WEBPASSWORD: ''
      VIRTUAL_HOST: '*'
      FTLCONF_LOCAL_IPV4: 127.0.0.1
    labels:
      traefik.enable: true
      traefik.http.routers.pihole.rule: Host(`pihole.$DOMAIN`)
      traefik.http.routers.pihole.entrypoints: https
      traefik.http.routers.pihole.tls: true
      traefik.http.routers.pihole.middlewares: authelia@docker
      traefik.http.routers.pihole.service: pihole
      traefik.http.services.pihole.loadbalancer.server.port: 80
