access_control:
  default_policy: deny
  rules:
    - domain:
        - auth.example.com # Authelia
        - internal.example.com
      networks:
        - 192.168.0.1/18
        - fe80::1/64
      policy: bypass
    - domain:
        - example.com
        - '*.example.com'
      policy: two_factor

identity_providers:
  # https://www.authelia.com/configuration/identity-providers/openid-connect/provider/
  oidc:
    hmac_secret: run `docker run authelia/authelia:latest authelia crypto rand --length 64 --charset alphanumeric`
    jwks:
      - key_id: RS256
        algorithm: RS256 # RS256, ES256, etc... # https://www.authelia.com/integration/openid-connect/introduction/#request-object
        
        # docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd)":/keys authelia/authelia:4 authelia crypto pair ecdsa generate --directory /keys
        key: |
          -----BEGIN PRIVATE KEY-----
          MII...
          -----END PRIVATE KEY-----

    lifespans:
      access_token: 1h
      authorize_code: 1m
      id_token: 1h
      refresh_token: 90m
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
        - userinfo
      allowed_origins:
        - https://site.example.com

    # https://www.authelia.com/integration/openid-connect/introduction/
    clients:
      - client_id: unique-id
        client_name: displayed in the authorization or recognized by the service
        client_secret: run `docker run --rm authelia/authelia authelia crypto hash generate pbkdf2 --variant sha512 --random --random.length 72 --random.charset rfc3986`
        public: false # Not required
        authorization_policy: two_factor # Not required
        redirect_uris:
          - https://site.example.com/callback
        scopes:
          - openid
          - profile
          - groups
          - email
          - offline_access
        userinfo_signing_algorithm: none # May be required
        token_endpoint_auth_method: client_secret_post # May be required

      # https://www.authelia.com/integration/openid-connect/synology-dsm/
      - client_id: synology-dsm
        client_name: Synology DSM
        client_secret: insecure_secret
        redirect_uris:
          - https://synology-dsm.$DOMAIN
        scopes:
          - openid
          - profile
          - groups
          - email
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: client_secret_post

      # https://www.authelia.com/integration/openid-connect/outline/
      - client_id: outline
        client_name: Outline
        client_secret: insecure_secret
        redirect_uris:
          - https://outline.$DOMAIN/auth/oidc.callback
        scopes:
          - openid
          - profile
          - email
          - offline_access
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: client_secret_post

      # https://www.authelia.com/integration/openid-connect/portainer/
      - client_id: portainer
        client_name: Portainer
        client_secret: insecure_secret
        redirect_uris:
          - https://portainer.$DOMAIN
        scopes:
          - openid
          - profile
          - groups
          - email
        userinfo_signed_response_alg: none
