access_control:
  default_policy: deny
  networks:
    - name: internal
        networks:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/18
  rules:
    - domain:
        - auth.example.com # Authelia
      policy: bypass
    - domain:
        - example.com
        - '*.example.com'
      policy: two_factor
