services:
  vaultwarden:
    container_name: vaultwarden
    hostname: vaultwarden
    image: vaultwarden/server:alpine
    restart: unless-stopped
    network_mode: bridge
    expose:
      - 80
      - 3012
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /run/mysqld/mysqld.sock:/tmp/mysql.sock:ro
      - $DATA_PATH:/data:rw
    environment:
      WEBSOCKET_ENABLED: true
      DATABASE_URL: $DATABASE_URL
      DOMAIN: https://vw.$DOMAIN
      SMTP_HOST: $SMTP_HOST
      SMTP_FROM: $SMTP_FROM
      SMTP_PORT: 465
      SMTP_SECURITY: force_tls
      SMTP_USERNAME: $SMTP_USERNAME
      SMTP_PASSWORD: $SMTP_PASSWORD
    labels:
      traefik.enable: true
      traefik.http.routers.vw.rule: 'Host(`vw.$DOMAIN`) || Host(`vw.$DOMAIN`) && Path(`/notifications/hub/negotiate`)'
      traefik.http.routers.vw.entrypoints: https
      traefik.http.routers.vw.tls: true
      traefik.http.routers.vw.service: vw
      traefik.http.services.vw.loadbalancer.server.port: 80
      # WebSocket Support (https://github.com/dani-garcia/vaultwarden/wiki/Enabling-WebSocket-notifications)
      traefik.http.routers.vw-ws.rule: 'Host(`vw.$DOMAIN`) && Path(`/notifications/hub`)'
      traefik.http.routers.vw-ws.entrypoints: https
      traefik.http.routers.vw-ws.tls: true
      traefik.http.routers.vw-ws.service: vw-ws
      traefik.http.services.vw-ws.loadbalancer.server.port: 3012
    healthcheck:
      test: ['CMD-SHELL', '/healthcheck.sh']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # vaultwarden-backup:
  #   # https://registry.hub.docker.com/r/bruceforce/vaultwarden-backup
  #   container_name: vaultwarden-backup
  #   image: bruceforce/vaultwarden-backup:latest
  #   restart: on-failure
  #   network_mode: none
  #   depends_on:
  #     - vaultwarden
  #   volumes:
  #     - vaultwarden-data:/data:ro
  #     - /var/backup/vaultwarden:/backup:rw
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     BACKUP_ADD_DATABASE: false
  #     BACKUP_DIR: /backup
  #     TIMESTAMP: true
  #     DELETE_AFTER: 30
