# Requires `chmod 777 $DB_SOCKET_PATH`.

services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb:latest
    restart: unless-stopped
    network_mode: none
    shm_size: 128mb
    user: mysql
    command:
      - mariadbd
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --log-ddl-recovery=/var/lib/mysql/ddl_recovery.log
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - $DB_DATA_PATH/mariadb:/var/lib/mysql:rw
      - $DB_SOCKET_PATH/mariadb:/var/run/mysqld:rw
    environment:
      LANG: ja_JP.UTF-8
      MYSQL_ROOT_PASSWORD: $MARIADB_PASSWORD
    # https://mariadb.com/docs/server/server-management/install-and-upgrade-mariadb/installing-mariadb/binary-packages/automated-mariadb-deployment-and-administration/docker-and-mariadb/using-healthcheck-sh?q=Healthcheck.sh
    healthcheck:
      test: ['CMD-SHELL', 'healthcheck.sh --connect --innodb_initialized']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  postgresql:
    container_name: postgresql
    hostname: postgresql
    image: postgres:alpine
    restart: unless-stopped
    network_mode: none
    shm_size: 128mb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - $DB_DATA_PATH/postgresql:/var/lib/postgresql/data:rw
      - $DB_SOCKET_PATH/postgresql:/var/run/postgresql:rw
    environment:
      LANG: ja_JP.utf8
      POSTGRES_PASSWORD: $POSTGRESQL_PASSWORD
      POSTGRES_INITDB_ARGS: --locale-provider=icu --icu-locale=ja-JP
    # https://qiita.com/e_a_s_y/items/bf08ab1923f8b6f4630e
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis:
    container_name: redis
    hostname: redis
    image: redis:alpine
    restart: unless-stopped
    network_mode: none
    shm_size: 128mb
    command:
      - redis-server
      - --unixsocket
      - /var/run/redis/redis.sock
      - --unixsocketperm
      - '777'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - $DB_DATA_PATH/redis:/data:rw
      - $DB_SOCKET_PATH/redis:/var/run/redis:rw
    # https://stackoverflow.com/a/70706628
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli --raw incr ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
