identity_providers:
  oidc:
    # https://www.authelia.com/configuration/identity-providers/openid-connect/provider/
    hmac_secret: run `docker run --rm authelia/authelia:4 authelia crypto rand --length 64 --charset alphanumeric`
    jwks:
      # docker run --rm -u "$(id -u):$(id -g)" -v "$PWD/secrets":/secrets authelia/authelia:4 authelia crypto pair ecdsa generate --directory /secrets --file.private-key ecdsa-private.pem --file.public-key ecdsa-public.pem
      - key_id: ECDSA
        key: |
          {{- fileContent "/opt/secrets/ecdsa-private.pem" | nindent 10 }}
      # docker run --rm -u "$(id -u):$(id -g)" -v "$PWD/secrets":/secrets authelia/authelia:4 authelia crypto pair rsa generate --directory /secrets --file.private-key rsa-private.pem --file.public-key rsa-public.pem
      - key_id: RSA
        key: |
          {{- fileContent "/opt/secrets/rsa-private.pem" | nindent 10 }}

    lifespans:
      access_token: 1h
      authorize_code: 1m
      id_token: 1h
      refresh_token: 90m
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
        - userinfo
      allowed_origins:
        - https://site.example.com

    # https://www.authelia.com/integration/openid-connect/introduction/
    clients:
      - client_id: unique-id
        client_name: displayed in the authorization or recognized by the service
        client_secret: run `docker run --rm authelia/authelia:4 authelia crypto hash generate pbkdf2 --variant sha512 --random --random.length 72 --random.charset rfc3986`
        public: false # Not required
        authorization_policy: two_factor # Not required
        redirect_uris:
          - https://site.example.com/callback
        scopes:
          - openid
          - profile
          - groups
          - email
          - offline_access
        userinfo_signing_algorithm: none # May be required
        token_endpoint_auth_method: client_secret_post # May be required

      # https://www.authelia.com/integration/openid-connect/synology-dsm/
      - client_id: synology-dsm
        client_name: Synology DSM
        client_secret: insecure_secret
        redirect_uris:
          - https://synology-dsm.$DOMAIN
        scopes:
          - openid
          - profile
          - groups
          - email
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: client_secret_post

      # https://www.authelia.com/integration/openid-connect/outline/
      - client_id: outline
        client_name: Outline
        client_secret: insecure_secret
        redirect_uris:
          - https://outline.$DOMAIN/auth/oidc.callback
        scopes:
          - openid
          - profile
          - email
          - offline_access
        response_types:
          - code
        grant_types:
          - authorization_code
          - refresh_token
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: client_secret_post

      # https://www.authelia.com/integration/openid-connect/portainer/
      - client_id: portainer
        client_name: Portainer
        client_secret: insecure_secret
        redirect_uris:
          - https://portainer.$DOMAIN
        scopes:
          - openid
          - profile
          - groups
          - email
        userinfo_signed_response_alg: none
