access_control:
  default_policy: deny
  rules:
    - domain:
        - auth.example.com # Authelia
        - internal.example.com
      networks:
        - 192.168.0.1/18
        - fe80::1/64
      policy: bypass
    - domain:
        - example.com
        - '*.example.com'
      policy: two_factor