# https://www.authelia.com/configuration/storage/introduction/
storage:
  encryption_key: run `docker run --rm authelia/authelia:4 authelia crypto rand --length 64 --charset alphanumeric`
  mysql:
    password: insecure_secret
